
# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: db

development:
  <<: *default
  # database: postgres
  database: corottos_development
  username: postgres
  #username: corottos


test:
  <<: *default
  # database: postgres
  database: corottos_development
  username: postgres
  #username: corottos
  #database: Corottosecrets.yml

production:
  <<: *default
  database: Corottos_production
  username: Corottos
  password: <%= ENV['COROTTOS_DATABASE_PASSWORD'] %>
